# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure your secret_key_base is kept private
# if you're sharing your code publicly.

# at which port the service should listen
#information_service_url: 172.16.67.77:11300
#information_service_user: scalarm-dev
#information_service_pass: dev-scalarm-456


development:
  secret_key_base: 'b0ee2853fcea855e3a19724ab5d513c471b9ecc3a986c2dcb95335bf2c6e9784347fd1d412573ade42c34b31f3aedd4e8518e5044672266210149f0cd07f15fc'
  # at which port the service should listen
  information_service_url: localhost:11300
  information_service_user: scalarm
  information_service_pass: scalarm
  # if you want to communicate through HTTP
  information_service_development: true

test:
  secret_key_base: 'b0ee2853fcea855e3a19724ab5d513c471b9ecc3a986c2dcb95335bf2c6e9784347fd1d412573ade42c34b31f3aedd4e8518e5044672266210149f0cd07f15fc'
  # at which port the service should listen
  information_service_url: localhost:11300
  information_service_user: scalarm
  information_service_pass: scalarm
  # if you want to communicate through HTTP
  information_service_development: true

production:
  # it should be
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # TODO FIXME - remember to have different values on production
  secret_key_base: 'b0ee2853fcea855e3a19724ab5d513c471b9ecc3a986c2dcb95335bf2c6e9784347fd1d412573ade42c34b31f3aedd4e8518e5044672266210149f0cd07f15fc'

  # at which port the service should listen
  information_service_url: localhost:11300
  information_service_user: scalarm
  information_service_pass: scalarm
